### 1. Базовый поиск
GET {{Api_Host}}/movies/search?Text=batman
Accept: application/json

### 2. Поиск с годом
GET {{Api_Host}}/movies/search?Text=batman&Year=2005
Accept: application/json

### 3. Поиск только сериалов
GET {{Api_Host}}/movies/search?Text=game&Type=series
Accept: application/json

### 4. Пагинация — страница 1
GET {{Api_Host}}/movies/search?Text=batman&Page=1
Accept: application/json

### 5. Пагинация — страница 2
GET {{Api_Host}}/movies/search?Text=batman&Page=2
Accept: application/json

### 6. Полный пример
GET {{Api_Host}}/movies/search?Text=inception&Year=2010&Type=movie&Page=1
Accept: application/json

### 7. Ошибка — пустой запрос (должен вернуть ошибку)
GET {{Api_Host}}/movies/search?Text=
Accept: application/json

###

@Api_Host = http://localhost:5162